- name: Carbon Black Cloud
  hosts: all
  become: yes
  tasks:
  - name: ping the server
    ansible.builtin.ping:

  - name: Copy the file cb-psc-sensor
    ansible.builtin.copy:
      src: /root/cb-psc-sensor-rhel-2.13.2.1054252.tar
      dest: /root/cb-psc-sensor-rhel-2.13.2.1054252.tar

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /root/cb-psc-install
      state: directory
      mode: '0755'

  - name: extract carbon black cloud tar file
    ansible.builtin.unarchive:
      src: /root/cb-psc-sensor-rhel-2.13.2.1054252.tar
      dest: /root/cb-psc-install
      remote_src: yes

  - name: Run a script with ansible shell
    ansible.builtin.shell: sh /root/cb-psc-install/install.sh 25LDH52OWR4SWB7YRJH
    when: user_count.stdout == "0"

  - name: start and enable cbagentd
    ansible.builtin.service:
      name: cbagentd
      state: restarted
      enabled: yes
  
  - name: check if cbagent is installed
    ansible.builtin.shell: rpm -qa | grep cb-psc-sensor
      register: cb-psc-sensor_installed
      ignore_errors: True
      check_mode: False
      changed_when: False

  - name: print
    debug:
      msg: "cb-psc-sensor is installed"
    when: cb-psc-sensor_installed.rc == 0

  # Uninstall the cbc
  # rpm -e cb-psc-sensor