- name: Carbon Black Cloud
  hosts: all
  become: yes
  tasks:
  - name: ping the server
    ansible.builtin.ping:
  
  - name: Uninstall the cbagent if exists
    ansible.builtin.shell: rpm -e cb-psc-sensor
    ignore_errors: true

  # Uninstall the cbc
  # rpm -e cb-psc-sensor

  # How to create tar file
  # tar -cvf /root/my_ansible.tar .

  # How to copy tat file output to /tmp
  # tar -xvf my_ansible.tar -C /tmp